/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./src/components/player/AudioPlayer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IntegratedPlayer: typeof import('./src/components/player/IntegratedPlayer.vue')['default']
    Player: typeof import('./src/components/player/Player.vue')['default']
    PlayerArtist: typeof import('./src/components/player/PlayerArtist.vue')['default']
    PlayerBackground: typeof import('./src/components/player/PlayerBackground.vue')['default']
    PlayerControl: typeof import('./src/components/player/PlayerControl.vue')['default']
    PlayerCover: typeof import('./src/components/player/PlayerCover.vue')['default']
    PlayerLyric: typeof import('./src/components/player/PlayerLyric.vue')['default']
    PlayerProgressBar: typeof import('./src/components/player/PlayerProgressBar.vue')['default']
    PlayerTitle: typeof import('./src/components/player/PlayerTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
